# Generated by Django 2.2.4 on 2021-05-31 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_thought'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thought',
        ),
    ]
