# Generated by Django 2.2.4 on 2021-05-31 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_delete_thought'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like', models.ManyToManyField(related_name='loved', to='login_register.users')),
                ('own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mypost', to='login_register.users')),
            ],
        ),
    ]
