# Generated by Django 2.2.4 on 2021-06-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0004_thought'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thought',
        ),
    ]
