# Generated by Django 3.2.3 on 2021-06-07 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_about', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='users_app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='users_app.patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='patient_who_have_doctor',
            field=models.ManyToManyField(related_name='patient_doctor', through='users_app.Appointment', to='users_app.Patient'),
        ),
    ]
