# Generated by Django 3.2.3 on 2021-06-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_auto_20210607_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patient_who_have_doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ManyToManyField(related_name='doctors', to='users_app.Patient'),
        ),
    ]
